version: "3.9"

services:
  # MYSQL
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=otmaster
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      #- ./mysql_data:/var/lib/mysql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - PMA_HOST=mysql
    ports:
      - 8080:80

  # APP NODE
  ot-master:
    build: .
    environment:
      - BD_SYSTEM=mysql
      - DB_HOST=mysql
      - BD_PORT=3306
      - BD_NAME=otmaster
      - BD_USER=root
      - BD_PASSWORD=toor
      - JWT_SECRET=luis
    ports:
      - "8000:8000"
    links:
      - mysql

volumes:
  mysql-data: