version: "3.9"

services:

  # POSTGRESQL
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=otmaster
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  
  # APP NODE
  otmaster:
    build: .
    environment:
      - BD_SYSTEM=postgres
      - DATABASE_URL=postgresql://root:toor@postgres:5432/otmaster
      - JWT_SECRET=luis
    ports:
      - "8000:10000"
    #command: >
    #  sh -c "npx sequelize-cli db:migrate && npm start"
    links:
      - postgres
volumes:
  postgres-data: