version: "3.9"

services:
  # MYSQL
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=otmaster
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      # ./mysql_data:/var/lib/mysql
      # for production ->
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - PMA_HOST=mysql
    ports:
      - 8080:80

  # APP NODE
  otmaster:
    build: .
    environment:
      - BD_SYSTEM=mysql
      - DATABASE_URL=mysql://root:toor@mysql:3306/otmaster
      - JWT_SECRET=luis
    ports:
      - "8000:10000"
    #command: >
    #  sh -c "npx sequelize-cli db:migrate && npm start"
    links:
      - mysql

volumes:
  mysql-data: